### load the libraries
#install.packages("caret)
#install.packages('klaR')
#install.packages("e1071)
library("caret")
library(klaR)
library(e1071)

summary(Bin_Shanghai)
attach(Bin_Shanghai)
Shanghai_x<-subset(Bin_Shanghai,select=-Ranking_Bin)
Shanghai_y<-Ranking_Bin
svm_model_Shanghai<-svm(Shanghai_x,Shanghai_y,type="C-classification")
summary(svm_model_Shanghai)
Shanghai_predict<-predict(svm_model_Shanghai,Shanghai_x)
system.time(Shanghai_predict<-predict(svm_model_Shanghai,Shanghai_x))
table(Shanghai_predict,Shanghai_y)
Shanghai_svm_tune<-tune(svm, train.x = Shanghai_x, train.y = Shanghai_y, kernel="radial", ranges=list(cost=10^(-1:2),gamma=c(.5,1,2)))
print(Shanghai_svm_tune)
svm_model_Shanghai_after_tune<-svm(Ranking_Bin ~ ., data=Bin_Shanghai, type="C-classification", kernel="radial",cost=10,gamma=0.5)
summary(svm_model_Shanghai_after_tune)
Shanghai_predict_after_tune<-predict(svm_model_Shanghai_after_tune,Shanghai_x)
system.time(predict(svm_model_Shanghai_after_tune,Shanghai_x))
table(Shanghai_predict_after_tune,Shanghai_y)