### load the libraries
#install.packages("caret)
#install.packages('klaR')
#install.packages("e1071)
library("caret")
library(klaR)
library(e1071)

summary(Bin_World)
attach(Bin_World)
World_x<-subset(Bin_World,select=-Ranking_Bin)
World_y<-Ranking_Bin
svm_model_World<-svm(World_x,World_y,type="C-classification")
summary(svm_model_World)
World_predict<-predict(svm_model_World,World_x)
system.time(World_predict<-predict(svm_model_World,World_x))
table(World_predict,World_y)
World_svm_tune<-tune(svm, train.x = World_x, train.y = World_y, kernel="radial", ranges=list(cost=10^(-1:2),gamma=c(.5,1,2)))
print(World_svm_tune)
svm_model_World_after_tune<-svm(Ranking_Bin ~ ., data=Bin_World, type="C-classification", kernel="radial",cost=1,gamma=0.5)
summary(svm_model_World_after_tune)
World_predict_after_tune<-predict(svm_model_World_after_tune,World_x)
system.time(predict(svm_model_World_after_tune,World_x))
table(World_predict_after_tune,World_y)