### load the libraries
#install.packages("caret)
#install.packages('klaR')
#install.packages("e1071)
library("caret")
library(klaR)
library(e1071)

summary(Bin_Times)
attach(Bin_Times)
Times_x<-subset(Bin_Times,select=-Ranking_Bin)
Times_y<-Ranking_Bin
svm_model_Times<-svm(Times_x,Times_y,type="C-classification")
summary(svm_model_Times)
Times_predict<-predict(svm_model_Times,Times_x)
system.time(Times_predict<-predict(svm_model_Times,Times_x))
table(Times_predict,Times_y)
Times_svm_tune<-tune(svm, train.x = Times_x, train.y = Times_y, kernel="radial", ranges=list(cost=10^(-1:2),gamma=c(.5,1,2)))
print(Times_svm_tune)
svm_model_Times_after_tune<-svm(Ranking_Bin ~ ., data=Bin_Times, type="C-classification", kernel="radial",cost=1,gamma=0.5)
summary(svm_model_Times_after_tune)
Times_predict_after_tune<-predict(svm_model_Times_after_tune,Times_x)
system.time(predict(svm_model_Times_after_tune,Times_x))
table(Times_predict_after_tune,Times_y)